# -*- coding: utf-8 -*-
"""microloan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IP0YpiHxznqRH_BwVdq8fYu2jJwYxBre
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Set random seed
np.random.seed(42)

# Your existing dataset generation code
n_customers = 2000

data = {
'customer_id': range(1, n_customers + 1),
'age': np.random.randint(18, 65, n_customers),
'gender': np.random.choice(['Male', 'Female'], n_customers, p=[0.6, 0.4]),
'location': np.random.choice(['Urban', 'Rural', 'Semi-Urban'], n_customers, p=[0.5, 0.3, 0.2]),
'monthly_income': np.random.normal(800, 300, n_customers).clip(200, 2000),
'employment_status': np.random.choice(['Employed', 'Self-Employed', 'Unemployed'], n_customers, p=[0.4, 0.4, 0.2]),
'education_level': np.random.choice(['Primary', 'Secondary', 'Tertiary', 'None'], n_customers, p=[0.3, 0.4, 0.2, 0.1]),
'months_active': np.random.randint(3, 36, n_customers),
'avg_transaction_value': np.random.normal(50, 20, n_customers).clip(5, 200),
'transaction_frequency': np.random.poisson(15, n_customers).clip(1, 50),
'savings_balance': np.random.normal(200, 100, n_customers).clip(0, 1000),
'loan_amount': np.random.normal(500, 200, n_customers).clip(100, 1500),
'loan_term_days': np.random.choice([30, 60, 90], n_customers, p=[0.6, 0.3, 0.1]),
'interest_rate': np.random.normal(12, 3, n_customers).clip(5, 25),
'days_since_last_loan': np.random.randint(0, 365, n_customers),
'loan_repaid': np.random.choice([0, 1], n_customers, p=[0.3, 0.7])
}

df = pd.DataFrame(data)

# Add realistic correlations
df.loc[df['monthly_income'] > 1000, 'loan_repaid'] = np.random.choice([0, 1], len(df[df['monthly_income'] > 1000]), p=[0.1, 0.9])
df.loc[df['employment_status'] == 'Unemployed', 'loan_repaid'] = np.random.choice([0, 1], len(df[df['employment_status'] == 'Unemployed']), p=[0.6, 0.4])

# Add behavioral features
df['transaction_consistency'] = np.random.normal(0.7, 0.2, n_customers).clip(0, 1)
df['evening_transaction_ratio'] = np.random.beta(2, 5, n_customers)
df['weekend_transaction_ratio'] = np.random.beta(3, 4, n_customers)

# Prepare and train model (same as before)
features = ['age', 'monthly_income', 'months_active', 'avg_transaction_value',
'transaction_frequency', 'savings_balance', 'loan_amount', 'interest_rate',
'transaction_consistency', 'evening_transaction_ratio', 'weekend_transaction_ratio']

X = df[features]
y = df['loan_repaid']

categorical_features = ['gender', 'location', 'employment_status', 'education_level']
X_categorical = pd.get_dummies(df[categorical_features], drop_first=True)
X = pd.concat([X, X_categorical], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=10)
rf_model.fit(X_train_scaled, y_train)

df['repayment_probability'] = rf_model.predict_proba(scaler.transform(X))[:, 1]
df['predicted_repayment'] = rf_model.predict(scaler.transform(X))

df['income_category'] = pd.cut(df['monthly_income'],
bins=[0, 500, 1000, 1500, 2000],
labels=['Low', 'Medium', 'High', 'Very High'])

df['risk_segment'] = np.where(df['repayment_probability'] > 0.8, 'Low Risk',
np.where(df['repayment_probability'] > 0.5, 'Medium Risk', 'High Risk'))

# 🎯 CRITICAL: Save with SEMICOLON delimiter and French decimal format
df.to_csv('microloan_data_french.csv',
sep=';',
decimal=',',
index=False,
encoding='utf-8')

print("✅ NEW FILE CREATED: 'microloan_data_french.csv'")
print("📁 This file uses SEMICOLON delimiter and COMMA for decimals")
print("🇫🇷 Formatted for French system compatibility")

# Save the dataset as CSV file on your computer
df.to_csv('microloan_data.csv', index=False)

print("✅ File saved successfully!")
print("📁 File location: microloan_data.csv in your current directory")

# Save to a specific folder df.to_csv('C:/Users/YourUsername/Desktop/microloan_data.csv', index=False)

# Save the dataset directly to your Downloads folder
df.to_csv(r'C:\Users\hp\Downloads\microloan_data.csv', index=False)

print("✅ File saved successfully!")
print("📁 Location: C:\\Users\\hp\\Downloads\\microloan_data.csv")
print("📊 Dataset shape:", df.shape)

df.to_csv(r'C:\Users\hp\Downloads\microloan_dataa.csv', index=False)
print("File saved to Downloads folder")